### ISSUE TITLE
This line is error prone: 'redrawtime' exceeded - set regexpengine

### ISSUE THREAD

**Issue by zorgick** [samoshkin/dotvim#2]
I just wanted to warn you that [this command](https://github.com/samoshkin/dotvim/blob/e0990a702ea16dc9b6084f38b5b02d75067b7a19/vimrc#L1344) may ruin someone's experience with vim according to this [issue](https://github.com/HerringtonDarkholme/yats.vim/issues/25). I discovered that any language plugin for typescript (yats is the most popular and reliable for now) will break, with this error `'redrawtime' exceeded, syntax highlighting disabled`. I've tried all existing solutions for typescript, including async ones, but each one of them froze the editor (only force quit helped to solve that), or sometimes disabled highlighting for the whole .{ts|tsx} file. Due to the fact, that your config is rather popular, I think it is appropriate to remove this line.

**Comment by samoshkin** [comment]
@zorgick 

Yeah, I get the point. 

It's almost 1 year passed since I actively developed this project, so I don't remember why I opt in for explicit "regexengine" option. If it causes crashes, it makes sense to remove.

NOTE. This "dotvim" project was never meant to be shared and promoted to be used by the community. It's just my personal vimrc settings, and using Github as a backup option, and for the ease of install on new machines. It's more like "works on my machine" thing. 

Unfortunately, in a recent times I have little to zero free time to devote to my GH projects.

**Comment by zorgick** [comment]
I saw that warning. And I understand that each config is a more personal thing.

But since your videos are in top recommendations either on reddit or in google search results for vim keyword, and a lot of newbies will try to get your config (because you've done a really great job setting up your vim) and will face with typescript problems, they may fall into despair and abandon this amazing editor for a long time.

Anyway, thanks for understanding. Hope, you'll have more time to explore amazing features of the vim editor and share it with the world :)

**Comment by samoshkin** [comment]
@zorgick JFYI, that I completely reworked this Vim config, including the issue you wrote about half a year ago (sorry for being so late).

The primary change is breaking down the huge >3K LOC `vimrc` file into the individual files in a modular fashion.

Besides that:
- added formatting, linting support, language server + [coc.nvim](https://github.com/neoclide/coc.nvim), insert completion a.k.a. `Intellisense`
- statusline has been migrated from `airline` to [lightline](https://github.com/itchyny/lightline.vim)
- pick and open files either through [nnn](https://github.com/jarun/nnn) file manager or `NERDTree`
- ubiquitous use of `fzf` to search for different things: project files, MRU files, tags, help tags, commands, `ripgrep` project-wide search. Plus it includes live file preview as you search with a syntax highlighting.
- removed rarely used plugins, commands, mappings. Clean up all the stuff. Update to newer plugins and approaches as of the end of 2020.

If you're still interested, see [readme](https://github.com/samoshkin/dotvim/blob/master/readme.md) for more info, or checkout new and tiny config files.

In the same way in the next days I'm going to push the reworked version of my [dotfiles](https://github.com/samoshkin/dotfiles) repo, that complement this Vim config.

**Comment by zorgick** [comment]
Hello!
Thank you for reaching out! I'm glad to hear that!
Your work is a huge inspiration for me, and I'm happy to see that it is
getting an improvement. I can't count how many times your utils and
shortcuts saved my time and made the code development an easy process.
I will definitely check the update in the near future.
By the way, have you heard of the OSS project called neovim? You should
definitely check it out https://neovim.io/charter/ . It has been half a
year since I've been using it, and I can definitely say that it is a robust
and reliable instrument. So you might want to check it out.


ср, 13 янв. 2021 г., 4:28 Alexey Samoshkin <notifications@github.com>:

**Comment by samoshkin** [comment]
@zorgick I think about neovim from time to time, especially when completion popup in an insert mode blinks on type, but...what effort would it take to migrate my existing >2K LOC configs from Vim -> Neovim? What was your personal experience, did you find it tough or not? What key benefits could you mention comparing Neovim and Vim?

**Comment by zorgick** [comment]
Well, the migration process was tedious for me at that moment, because I
decided to opt to neovim, when I faced with the problem, that I later
addressed to you (about an old regex engine). But it doesn't mean this will
be the same for you. The main problem at that time was that I didn't know
vim quite well and I was lost in the 2K configuration file of yours. So I
was doing 4 things at that time. I was exploring vim and solving its
issues, I was figuring out your config, I was trying to write code in vim
for my job and I was migrating to neovim and solving its issues. In other
words, if you feel confident with vim, neovim will give you the same
feeling.

Personally, I find it more pleasant to work with out of the box. What
really gained my heart are asynchronous operations (semantics, code checks,
etc) and integrated terminal. Also lsp servers like in vscode (with vim-lsp
it is a fantastic solution), hover windows (in which you can jump into and
navigate there).
What I don't like is that it doesn't exist on linux OSes by default)) I
can't really recall any other cons of it.

Anyway, you can check my config for neovim
<https://github.com/zorgick/.dotfiles/blob/master/init.vim>and assure
yourself that it doesn't differ much from vim one's. Also bash_profile
config
<https://gist.github.com/zorgick/108b4d232491a15d9b954decd39633b5#file-bash_profile>
(ignore installation section) which is necessary for neovim

Here're screenshots to give you the idea of what it looks like inside: [image:
image.png][image: image.png]


пт, 15 янв. 2021 г. в 01:44, Alexey Samoshkin <notifications@github.com>:

**Comment by samoshkin** [comment]
Thanks. Checked out your `init.vim` file. Looks like a normal vimrc. I guess ~90% of the config should be compatible. It definitely worths giving `nvim` a try.

As I said before, let me share an update revision of my [dotfiles](https://github.com/samoshkin/dotfiles) repo. There're a lot of gems inside, except it lacks fully automated installation script. So it's better off just checking out the source code or maybe copy&paste some snippets.
